### ISSUE TITLE
No realtime info anymore since 0.9.5

### ISSUE THREAD

**Issue by PvdGulik** [rvdbreemen/OTGW-firmware#130]
After updating tot 0.9.5 everything seems to work fine. Still getting info in Domoticz and Homebridge. But missing the realtime info on de webpage of the OTGW it-self. I see the buttons Home and Advanced, and all the sub-pages under Advanced. But nowhere the info on the Home-page as in 0.9.3. I'm not sure if I runnen 0.9.4. so cannot confirm that is worked in 0.9.4.

But is seems like it changed with the new Layout.

In the left-under corner is says: PS=1, no UI-updates. I tried to set it to PS=0, but that did not solve the problem.

Thanks!

**Comment by rvdbreemen** [comment]
When it says PS=1, no UI-updates. It detected a PS=1 command, after that the PIC goes quiet and does no longer provide the update OT data id's so that they can be decoded by the firmware. So the data is simply not forwarded to the firmware, not sure what is going on. Could you do a debug log (port 23) and to show what is going on?

**Comment by rvdbreemen** [comment]
@PvdGulik without additional information I cannot help or change behavior.
