### ISSUE TITLE
Alway needed to update mklittlefs with update OTGW-firmware?

### ISSUE THREAD

**Issue by PvdGulik** [rvdbreemen/OTGW-firmware#33]
Thanks for again a upgrade, good work!

What I wonder is if it is necessary to always update mklittlefs while update OTGW-firmware.
I don't think so, only after updating to 0.7.2. Maybe you could mention that in the readme file.
This wil prevent need to download your settings, because updating mklittlefs loose your settings.

Thanks!

**Comment by rvdbreemen** [comment]
If I remember correctly there always have been updates and fixes to the javascript and mqttha.cfg as well. This is due to the fact that the settings are slowly being expanded. This causes updates to the data on the littlefs filesystem. If you do not want to setup your device each time, you can download the settings file (*.ini) and just flash the binary littlefs and upload the *.ini afterward, and reboot.

This saves you of reconfiguring each time.

The short answer, yes, it's needed to update the littlefs each time (at least in the last few releases).
